M48
; DRILL file {KiCad 6.0.9-8da3e8f707~116~ubuntu20.04.1} date pet 23 dec 2022 11:35:50
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-12-23T11:35:50+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.9-8da3e8f707~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
%
G90
G05
T1
X124.775Y-107.315
X131.775Y-107.315
T0
M30
